In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import time
import glob
%matplotlib inline
from sklearn import preprocessing
import tables
import h5py
from sqlalchemy import create_engine

In [3]:
flights_w = pd.read_csv('flights_weather_V2.csv')
flights_w.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (14,15,16,17,19,20,24,25,26,27,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0   MONTH_NAME  DOW_NAME AIRLINE ORIGIN_AIRPORT  \
0           0  01- January  Thursday      AS            ANC   
1           1  01- January  Thursday      AS            ANC   
2           2  01- January  Thursday      DL            ANC   
3           3  01- January  Thursday      AS            GEG   
4           4  01- January  Thursday      AA            LAX   

  DESTINATION_AIRPORT  DEPARTURE_SCHEDULED  DISTANCE    ARRIVAL_SCHEDULED  \
0                 SEA  2015-01-01 09:05:00      1448  2015-01-01 13:30:00   
1                 SEA  2015-01-01 09:45:00      1448  2015-01-01 14:09:00   
2                 SEA  2015-01-01 09:45:00      1448  2015-01-01 14:15:00   
3                 SEA  2015-01-01 13:00:00       224  2015-01-01 14:10:00   
4                 PBI  2015-01-01 08:10:00      2330  2015-01-01 15:50:00   

   ARRIVAL_DELAY      ...        arr_temp  arr_dew arr_hum arr_windspd  \
0          -22.0      ...           28.94    21.92   74.70        0.00   
1          -14.0      ...           28.94    21.92   74.70        0.00   
2          -24.0      ...           28.94    21.92   74.70        0.00   
3            0.0      ...           28.94    21.92   74.70        0.00   
4           -9.0      ...           75.92    69.98   81.85        3.00   

  arr_precip dept_alti_y dept_vsby_y dept_gust_y  dept_sky_y dept_weather_y  
0        0.0       30.32        10.0           M         CLR              M  
1        0.0       30.32        10.0           M         CLR              M  
2        0.0       30.32        10.0           M         CLR              M  
3        0.0       30.32        10.0           M         CLR              M  
4        0.0       30.21       10.00           M         FEW              M  

[5 rows x 34 columns]

In [ ]:
>>> le = preprocessing.LabelEncoder()
>>> le.fit([1, 2, 2, 6])
LabelEncoder()
>>> le.classes_
array([1, 2, 6])
>>> le.transform([1, 1, 2, 6]) 
array([0, 0, 1, 2]...)
>>> le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])